# Generated by Django 5.0.6 on 2024-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('microrregiao_nome', models.CharField(max_length=200)),
                ('mesorregiao_nome', models.CharField(max_length=200)),
                ('uf_sigla', models.CharField(max_length=2)),
                ('uf_nome', models.CharField(max_length=200)),
                ('regiao_nome', models.CharField(max_length=200)),
            ],
        ),
    ]
